{
  "headers": {
    "server": "nginx",
    "content-type": "text/html; charset=UTF-8",
    "x-drupal-dynamic-cache": "MISS",
    "link": "<https://www.mulesoft.com/>; rel=\"shortlink\", <https://www.mulesoft.com>; rel=\"canonical\"",
    "link": "</sites/default/files/css/css_6R56SeEnTvVixGDiGLUG8b6dBCQpl1L296MeOqbxlZQ.css>; rel=preload; as=style",
    "link": "</sites/default/files/css/css_xnDtv5yC1gcgT1B3amiKR793qT6Jt1GDBKI30-z2ioU.css>; rel=preload; as=style",
    "link": "</sites/default/files/css/css_0U479Eejx37XuGNOJDwnQEFwl66_Blch-mwNa71KQSI.css>; rel=preload; as=style",
    "link": "</sites/default/files/css/css_qU0JECTSPHw4O5zbNHTgNmT2tTbYSjEx94C9OBCzN8Y.css>; rel=preload; as=style",
    "link": "</sites/default/files/js/js_c8LbWbHV1txem3q8oAzuadnL-HiBShaQH_WRviNqT_g.js>; rel=preload; as=script",
    "link": "</sites/default/files/js/js_4nw5b11a5uQMyEbh4zXqGm6RwTXg5qzkOOGDxcNnQhw.js>; rel=preload; as=script",
    "link": "</sites/default/files/js/js_Zw-B0nEMAnVgZWLR89Pkbr9CFuKNDyi0j9HTUYBznkc.js>; rel=preload; as=script",
    "x-ua-compatible": "IE=edge",
    "content-language": "en",
    "x-content-type-options": "nosniff",
    "x-frame-options": "ALLOW-FROM https://resources.mulesoft.com/",
    "last-modified": "Thu, 12 Nov 2020 20:34:18 GMT",
    "etag": "\"1605213258\"",
    "x-drupal-cache": "HIT",
    "x-request-id": "v-f6332726-2526-11eb-9e15-6374cd7eecfe",
    "x-ah-environment": "prod",
    "x-cache-hits": "20",
    "x-age": "177",
    "cache-control": "public, max-age=604800",
    "expires": "Sun, 22 Nov 2020 20:56:49 GMT",
    "date": "Sun, 15 Nov 2020 20:56:49 GMT",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "connection": "Transfer-Encoding",
    "content-security-policy": "frame-ancestors https://library.mulesoft.com https://resources.mulesoft.com 'self'",
    "strict-transport-security": "max-age=63072000; preload"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}